---
image: python:latest

include:
  - template: Dependency-Scanning.gitlab-ci.yml

variables:
  build_cache: ${CI_PROJECT_DIR}/build_cache
  DS_PYTHON_VERSION: 3
  DS_PIP_VERSION: "20.0.2"
  PIP_REQUIREMENTS_FILE: requirements.txt
cache:
  paths:
    - ${CI_PROJECT_DIR}/build_cache
  key: ${CI_PROJECT_ID}

services:
  - docker:dind

stages:
  - test
  - build
# before_script:
#   - apt-get update && apt-get install make
#   - python3 --version

pylint:
  stage: test
  extends: .pipelinesetup
  script:
    - pip3 install --upgrade pylint pylint-exit anybadge
    - mkdir ./pylint
    - cd ./module && pylint *  -f parseable --ignore-imports=yes --output-format=text . | tee ../pylint/pylint.log || pylint-exit $? && cd -
    - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
    - anybadge --label=Pylint --file=pylint/pylint.svg --value=$PYLINT_SCORE 2=red 4=orange 8=yellow 10=green
    - echo "Pylint score is $PYLINT_SCORE"
  artifacts:
    paths:
      - ./pylint/

code_quality:
  stage: test
  extends: .pipelinesetup
  script:
    - pip3 install mypy
    - mypy --strict module/main/venvctl.py
    - mypy --strict module/tests/unit.py
    - mypy --strict module/utils/reports.py
    - mypy --strict module/utils/tools.py
    - mypy --strict module/cli/main.py
  allow_failure: true

unit:
  stage: test
  extends: .pipelinesetup
  script:
    - python -m module generate --config ./module/tests/config/venvs.json --out ${CI_PROJECT_DIR}/build_cache/venvs_unit
    - rm -rf ${CI_PROJECT_DIR}/build_cache/venvs_unit

coverage:
  stage: test
  extends: .pipelinesetup
  script:
    - pip3 install codecov
    - coverage run -m module.tests.unit
    - coverage report -m
    - coverage html -d ${CI_PROJECT_DIR}/build_cache/tests/coverage
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

build:
  stage: build
  extends: .pipelinesetup
  script:
      - rm -rf ${CI_PROJECT_DIR}/build_cache/venvs
      - pip3 install --upgrade -r requirements.txt
      - pip3 install --upgrade venvctl
      - python -m venvctl generate --config ./module/tests/config/venvs.json --out ${CI_PROJECT_DIR}/build_cache/venvs
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/build_cache/venvs

.pipelinesetup:
  before_script:
    - mkdir -p $build_cache
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
    - python --version
